apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argo-guard
spec:
  version: v1
  # Transition bundles fetch the last successfully synced Git revision.
  provideGitCreds: true
  discover:
    find:
      glob: "**/kustomization.yaml"
  generate:
    command: ["argo-guard", "generate"]
